config = {'model': {'input_dim': 784,
           'hidden_dim': 256,
           'num_classes': 10,
           'depth': 2,
           'sigma': 0.5,
           'local_init': True,
           'detach_operands': False},
 'train': {'seed': 123,
           'epochs': 50,
           'batch_size': 64,
           'learning_rate': 0.001,
           'clip_max_norm': 0,
           'num_threads': 1,
           'save_dir': 'results/mnist/wiring/depth_02/width_256/local_sigma_0p5/seed_123'},
 'data': {'root': 'datasets', 'threshold': 0.5, 'validation_fraction': 0.0, 'dataset': 'mnist'}}
